name: dynamic_schema_mapper
description: Automatically map dynamic backend JSON to type-safe Dart structures at runtime without model classes. Perfect for evolving APIs.
version: 0.1.0
homepage: https://github.com/SamarthGarge/dynamic_schema_mapper
repository: https://github.com/SamarthGarge/dynamic_schema_mapper

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - json
  - parsing
  - serialization
  - dynamic
  - backend